name: fact-flick-run-build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use API key
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm install

      - name: Run React Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: npm run deploy

      - name: Set Git user identity
        run: |
          git config user.email "ericjyr@gmail.com"
          git config user.name "ericjyr"
